export * from './menu.page';
export * from './preferences.page';
export * from './system.page';
export * from './error.page';
export * from './nothing.page';
export * from './collections.page';
export * from './collection.page';
export * from './games.page';
export * from './help.page';
